@startuml
title **Augmint** - Contract dependencies
skinparam ArrowColor #blue
skinparam noteBackgroundColor #lightgrey

artifact StabilityBoardSigner
artifact Rates
artifact AugmintReserves
artifact FeeAccount
artifact AugmintToken
artifact InterestEarnedAccount
artifact MonetarySupervisor
artifact LoanManager
artifact Locker
artifact Exchange


rectangle "Legend" #Beige {
	artifact contract1
	artifact contract2
    artifact contract3
	artifact contract4
    contract1 ==>> contract2 : Dependency without setter\nChange via new deployment
    contract3 ..>> contract4 : Amendable dependency\nChange via setter or Restricted.grantPermission
}

AugmintToken ..>> FeeAccount
AugmintToken ..>> StabilityBoardSigner

MonetarySupervisor ==>> AugmintToken
MonetarySupervisor ..>> StabilityBoardSigner
MonetarySupervisor ..>> AugmintReserves
MonetarySupervisor ..>> InterestEarnedAccount

LoanManager ==>> AugmintToken
LoanManager ..>> StabilityBoardSigner
LoanManager ..>> MonetarySupervisor
LoanManager ..>> Rates

Locker ==>> AugmintToken
Locker ..>> StabilityBoardSigner
Locker ..>> MonetarySupervisor

Exchange ==>> AugmintToken
Exchange ..>> StabilityBoardSigner
Exchange ..>> Rates
Exchange ..>> FeeAccount

InterestEarnedAccount ..>> StabilityBoardSigner

FeeAccount ..>> StabilityBoardSigner

AugmintReserves ..>> StabilityBoardSigner

@enduml
