@startuml
title **Augmint** - Lock flow
skinparam ArrowColor #blue
skinparam noteBackgroundColor #lightgrey

actor Depositor
control AugmintToken
control Locker
control MonetarySupervisor
control InterestEarnedAccount
actor Releaser

== Locking funds ==
Depositor -> AugmintToken : transferAndNotify\n(address: Locker, value: lockAmount, data: lockProductId)

activate AugmintToken
    AugmintToken -> AugmintToken : _transfer(Depositor, Locker, lockAmount, "")
    Depositor --> Locker : lockAmount transferred
    AugmintToken -> Locker : transferNotification\n(sender: AugmintToken, origin: Depositor, lockAmount, data: lockProductId)
deactivate AugmintToken

activate Locker
    Locker -> Locker : checks & create new lock
    Locker -> MonetarySupervisor : lockFunds\n(lockAmount, interestAmount)\n//Q: function name?//
    note over MonetarySupervisor
        lockFunds is restricted to
        trusted Locker contract(s)
    end note
deactivate Locker

activate MonetarySupervisor
    MonetarySupervisor -> MonetarySupervisor : enforce limits + update KPIs
    MonetarySupervisor -> InterestEarnedAccount : accrueInterest(Locker, interestAmount)
deactivate MonetarySupervisor

activate InterestEarnedAccount
    note over InterestEarnedAccount
        accrueInterest is restricted to
        MonetarySupervisor contract
    end note
    InterestEarnedAccount -> AugmintToken : transfer(Lender, interestAmount)
    InterestEarnedAccount --> Locker : lock interest transfered
    InterestEarnedAccount -> MonetarySupervisor : success (accrueInterest)
deactivate InterestEarnedAccount

MonetarySupervisor -> Locker : success (lockFunds)

activate Locker
    Locker -> Locker : emmit events
deactivate Locker

== Release funds  ==
Releaser -> Locker : releaseFunds(lockId)
note left
    releaseFunds() is not restricted
    caller will be rewarded
    (to be implemented later + releaseMultiple)
end note

activate Locker
    Locker -> Locker : checks if release time passed
    Locker -> MonetarySupervisor : releaseFundsHouseKeeping\n(Depositor, lockAmount, interestAmount)\n//Q: fx name?//
deactivate Locker

activate MonetarySupervisor
    note over MonetarySupervisor
        releaseFundsHouseKeeping is restricted to
        trusted Locker contract(s)
    end note
    MonetarySupervisor -> MonetarySupervisor : update KPIs
deactivate MonetarySupervisor

MonetarySupervisor -> Locker : success (releaseFundsHouseKeeping)

activate Locker
    Locker -> AugmintToken : transfer(Depositor, lockAmount + interestAmount)
    Locker --> Depositor : lockAmount + interest transfered
Locker -> Locker : emmit events
deactivate Locker
@enduml
